version: '3'
services:
    postgres:
        image: postgres:11
        container_name: payment-postgres
        restart: always
        environment:
            - POSTGRES_DB=payment
            - POSTGRES_USER=payment
            - POSTGRES_PASSWORD=payment
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
    mongodb:
        container_name: payment-mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: payment
            MONGO_INITDB_ROOT_PASSWORD: payment
        volumes:
            - ./docker/mongodb/entrypoints/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./docker/mongodb/data:/data/db
