version: '3'
services:
    postgres:
        image: postgres:11
        container_name: payment-postgres
        restart: always
        environment:
            - POSTGRES_DB=payment
            - POSTGRES_USER=payment
            - POSTGRES_PASSWORD=payment
        ports:
            - 5432:5432
